### ISSUE TITLE
По даблклику на поле с заданием под диаграммой сделать это поле редактируемым

### ISSUE THREAD

**Issue by oganesjan** [dturevski/olive-gui#15]
При двойном щелчке мыши на поле с заданием (которое прямо под диаграммой, см. ниже) сделать это поле редактируемым, "синхронизировав" его с полем "Задание" ("Stipulation") в правой части окна.

![image](https://user-images.githubusercontent.com/45603874/70608739-abc41e80-1c11-11ea-9ef6-d9877db93e3a.png)

**Comment by dturevski** [comment]
Added in v1.1
