### ISSUE TITLE
Configurable memory amount when launching Popeye

### ISSUE THREAD

**Issue by vlaicu** [dturevski/olive-gui#17]
When running Popeye from Olive shell, the system allocates by default 512 MB.
It would be nice to be able to configure manually the memory amount.

**Comment by dturevski** [comment]
Starting from version 1.0 the amount of memory can be specified in UI, on the "Popeye" tab there is a field labeled "Hashables (Mb)". In the older versions the amount of memory is configured by editing the olive config file (close all instances of olive before editing the configs).
