### ISSUE TITLE
olive 1.3 doesn't run properly in a case with dummy or dummy pawn

### ISSUE THREAD

**Issue by andrew-buchanan** [dturevski/olive-gui#29]
Hi thanks for all your work - Olive is fabulous.
(1) First: h#6 intelligent problems P1359493 and P1375440 run fine, with promonly Q R S B DU in the second case. Only odd thing is that the solution in the second case begins 1.c2-c1=TI. Don't know what a "TI" is - not in the list of fairy pieces.
(2) Now I try to run 5P2/6B1/8/8/3p4/8/2p2P2/k5K1 with promonly Q R S B P. It basically never comes back. 
(3) If instead I try to replace wPf8 with wDU, it finds the solution (beginning 1.c2-c1) and does nothing for a while. When I select the window, an error pop-ups where you can't copy the text comes up, saying olive-1.3 Failed to run popeye executable (pywin64.exe). 
I am running 64 bit laptop. Hope this is enough for you to diagnose.

**Comment by dturevski** [comment]
Hi Andrew, thanks.

This looks very much like a Popeye issue. "TI" is "Total Invisible". Could you please copy and paste the popeye inputs that are causing these? It's the text in "Popeye" tab, starts with "BeginProblem".

**Comment by thomas-maeder** [comment]
Definitely a Popeye problem.
