### ISSUE TITLE
Feature request: tab "Pieces" - section "Fairy" - initialize with fairy piece types occuring in current problem

### ISSUE THREAD

**Issue by thomas-maeder** [dturevski/olive-gui#3]
When I load a problem, the section "Fairy" is empty.
It would be helpful if the section were intialized with the fairy piece types used by the current problem.

**Comment by dturevski** [comment]
That may not always be the desired behavior, I'm thinking about having an option in context menu like "Populate from current entry".

**Comment by dturevski** [comment]
Fixed
