### ISSUE TITLE
Shifting position with Type1(2,3)

### ISSUE THREAD

**Issue by oganesjan** [dturevski/olive-gui#34]
1) point out the condition which has a parameter Type1, Type2, Type3 (for example, SingleBox or RepublicanChess);
2) shift a position to the left or to the right;
3) launch a testing.

As a result, a fragment "**e1**" in the word "Typ**e1**" will be shifted "to the left (right)" too - it will be "Typ**f1**", for example:

![image](https://user-images.githubusercontent.com/45603874/126626760-566492b3-990c-456e-935e-eb77cd0a3c8a.png)

**Comment by dturevski** [comment]
Fixed in 1.5
