### ISSUE TITLE
Improved RTF

### ISSUE THREAD

**Issue by 5reddman** [dturevski/olive-gui#39]
At the moment, bracketed entries in "source:" are rendered as such in the RTF view. For example:

source: 
  name: 'The Cook'
  issue:  3
  problemid:  1
  year:  1975 
  month:   9

internally stores as 

source: '{"name": 'The Cook', ''issue'': 3, ''problemid'': 1, ''year'': 1975, ''month'': 9}'

and is also rendered in RTF this way;  preferable would be

"The Cook 3, 9/1975, Nr. 1" or whatever.

Hauke

**Comment by dturevski** [comment]
Template for the entry header was added in 1.5, see the release notes for more details.
