### ISSUE TITLE
Feature request: Add copy of current problem

### ISSUE THREAD

**Issue by thomas-maeder** [dturevski/olive-gui#4]
When composing a problem, it is helpful to keep "snapshots" of some stages of the composition process.

This could be achieved by
- adding a copy of the current problem
- switching to that copy for continuing

**Comment by dturevski** [comment]
There are already several ways to do this in 0.13.6
1) "File" - "Save template": all new entries will be a copy of the current entry (template)
2) In the problem list (bottom right) right-click and select "Copy" to copy an entry. Later right-click and "Paste" to create a copy of the problem. Multiple selection is supported. You can cut and paste to reorder problems in a collection. You can copy and past between several instances of olive to compile collections. You can copy and paste between olive and yacpdb (they have same format).
