### ISSUE TITLE
pyrcc5 doesn't exist

### ISSUE THREAD

**Issue by rchastain** [dturevski/olive-gui#49]
Hello! I have just tried to install Olive GUI (on Linux Mageia), following the steps indicated in _README.md_. I get an error saying that **pyrcc5** doesn't exist. What did I do wrong?

Sorry if this is a stupid question. Attached a file where you can see which commands I typed and the resulting output.

[commands.log](https://github.com/dturevski/olive-gui/files/7694223/commands.log)

**Comment by dturevski** [comment]
In your log:
```
pip3 install PyQt5
Requirement already satisfied: PyQt5 in /usr/lib64/python3.8/site-packages (5.15.2)
```
`pyrcc5` normally should come with the `PyQt5`. Perhaps you can try upgrading PyQt5 (`pip3 install PyQt5 --upgrade`) or try to install it from the distro (the package name should be something like python3-pyqt5-dev, sorry I'm not familiar with Mageia).

Also it's worth checking if `pyrcc5` was actually installed, but you can't run it for some reason (paths? permissions?). It could be as easy as putting in the correct path in the Makefile.

Please let me know if anything worked.

**Comment by dturevski** [comment]
Looking some more at your log I've noticed this
```
 WARNING: The script markdown_py is installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Could this be the reason the `pyrcc5` is not found too? `/usr/local/bin` is in the PATH.

**Comment by rchastain** [comment]
> `pyrcc5` normally should come with the `PyQt5`. Perhaps you can try upgrading PyQt5 (`pip3 install PyQt5 --upgrade`) or try to install it from the distro (the package name should be something like python3-pyqt5-dev, sorry I'm not familiar with Mageia).
> 
Thank you for your answer. With your indications, I could solve the problem. I installed **python3-qt5** and **python3-qt5-devel**, using the package manager. If I trust the package manager, they were not installed. After that I could start Olive successfully.
Regards.
Roland
