### ISSUE TITLE
Missing dependency on Linux

### ISSUE THREAD

**Issue by dcolazin** [dturevski/olive-gui#57]
Tested on Ubuntu 20.04.5. After doing `sudo make dependencies`, doing `make resources.py` causes

```
pyrcc5 -o resources.py resources/olive.qrc
make: pyrcc5: Command not found
make: *** [Makefile:20: resources.py] Errore 127
```

which is easily solved after installing `pyqt5-dev-tools` (for example with `sudo apt install pyqt5-dev-tools`). While the command to install qt might be OS-dependant, a note on the readme would be nice, something like "The prerequisites are Python3 (with pip and pyqt5-dev-tools), git and make".

**Comment by dturevski** [comment]
That's odd. The resource compiler `pyrcc5` should have been installed by `make dependencies` in an OS independent way (with `$PIP install PyQt5`).
Could it be that they moved it to some other PIP package?
Anyway, thanks, I'll investigate it further!

**Comment by dturevski** [comment]
Sorry, can't confirm. I'm using a fresh install of Ubuntu 22.04.1 LTS in VirtualBox.
```
$ sudo apt-get update
$ sudo apt-get install build-essential
$ sudo apt-get install git
$ sudo apt-get install python3-pip
$ git clone https://github.com/dturevski/olive-gui.git
$ cd olive-gui
$ sudo make dependencies
$ which pyrcc5
/usr/local/bin/pyrcc5
$ make resources.py
$ ls -lA resources.py
-rw-rw-r-- 1 dima dima 1561877 oct 19 13:48 resources.py
```

Could it be that you don't have `/usr/local/bin/` on the `PATH`?

**Comment by dcolazin** [comment]
No, I have `/usr/local/bin/`... interesting, I will try to understand what happened, thank you!
